### ISSUE TITLE
PIP seems to disregard numpy requirement

### ISSUE THREAD

**Issue by LinguList** [lingpy/lingpy#156]
I was just notified by @evoling that a python install of LingPy in py3 environment with pip wouldn't recognize numpy as a dependency. This is strange for me, since it passes all tests, but we should try to look into it...

**Comment by evoling** [comment]
To replicate:

```sh
virtualenv --python=python3 lingpy-py3
cd lingpy-py3
. bin/activate
pip install lingpy
```

**Comment by xrotwang** [comment]
I can replicate this problem. PIP actually does pick up the dependency and downloads `numpy`. But installation fails, because not only `lingpy`,  but `setup.py install` depends on `numpy`, i.e. cannot be run withouth `numpy` installed. I think this is just one more effect of importing from the package to be installed within `setup.py`, which therefore should be avoided.

**Comment by xrotwang** [comment]
It should be noted, though, that this should not happen with current `HEAD`. But this issue also wouldn't be caught by the integration tests run on Travis, because we [install `numpy` before](https://github.com/lingpy/lingpy/blob/master/.travis.yml#L23) running `setup.py install` on `lingpy`.

**Comment by LinguList** [comment]
Allright! That then reduces the problem to older versions of LingPy, since the prior import is no longer necessary in the actual version. And once we launch a new release, it should'nt occur anymore. Question is now: should we close this issue for the time being, since it will be solved with the new actual release, or should we make some bug-fix release for this current HEAD and upload it to pypi?

**Comment by xrotwang** [comment]
I would say this issue is worked around easy enough by installing `numpy` manually, so would rather just mention this in the [installation instructions](http://lingpy.org/tutorial/installation.html).

**Comment by LinguList** [comment]
Allright, dunnit by adding it directly to the HTML on the website.
