### ISSUE TITLE
Fix object initialization for LexStat

### ISSUE THREAD

**Issue by xrotwang** [lingpy/lingpy#171]
While writing tests I came across this behaviour, that highlights a couple of problems:

``` python
>>> from lingpy import LexStat
>>> l = LexStat(None, defaults=True)
>>> l
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lingpy/compare/lexstat.py", line 324, in __repr__
    return "<lexstat-model {0}>".format(self.filename)
  File "lingpy/basic/parser.py", line 454, in __getattr__
    if attr in self._alias:
  File "lingpy/basic/parser.py", line 452, in __getattr__
    return self.__getattribute__(attr)
AttributeError: 'LexStat' object has no attribute '_alias'
```
1. There is this intended functionality of returning the default keyword parameters when `defaults=True` is passed. This does not work for object initialization, though. So `l` above is not the `dict` of keyword parameters.
2. The exception is raised trying to run `repr` on the `LexStat` instance. Due to the functionality explained in 1., the object is not fully initialized, so it has no attribute `_alias`. Another reason to not return early from object initialization!

**Comment by LinguList** [comment]
I just checked, this is fixed by now.
