### ISSUE TITLE
Pairwise module 

### ISSUE THREAD

**Issue by PhyloStar** [lingpy/lingpy#182]
Pairwise module does not work for sequence of IPA strings. The error is:

File "/usr/local/lib/python2.7/dist-packages/lingpy-2.4.2-py2.7.egg/lingpy/align/pairwise.py", line 80, in __init__
    for k,(seqA,seqB) in enumerate(self.seqs):
ValueError: too many values to unpack

**Comment by LinguList** [comment]
please submit the code you entered, otherwise we can't debug...

**Comment by LinguList** [comment]
only from the error, without the input data, there's nothing we can do...

**Comment by PhyloStar** [comment]
from lingpy import *
seqs = [u"gətraku",u"batʧi"]
pair = Pairwise(seqs)

**Comment by LinguList** [comment]
that won't work, you need to write:

```python
pair = Pairwise(*seqs)
```
you need to pass either two sequences (seqA, seqB), or a two-dimensional list of sequence pairs: [http://lingpy.org/docu/align/lingpy.align.Pairwise.html#lingpy.align.Pairwise](http://lingpy.org/docu/align/lingpy.align.Pairwise.html#lingpy.align.Pairwise)
