### ISSUE TITLE
Remove output to stdout when running tests

### ISSUE THREAD

**Issue by xrotwang** [lingpy/lingpy#194]
During tests, all output to `stdout` should be suppressed. Right now, this can partly be achieved by setting the log level in the LingPy config file to `CRITICAL`, but ideally, during test runs local configuration shouldn't interfere. In addition there are quite a few `print` calls left in the code which should be made conditional on log levels as well.

**Comment by LinguList** [comment]
I just took care of the print-commands and erased them,unless they're part of the design, as in "bcubes", where the keyword pprint can print stuff to stdout ( will suggest a PR soon, ).

Regarding the question of suppressing this other than via log-level, I am not clear how this could be done...

**Comment by xrotwang** [comment]
I'm looking into this. Probably something based on [Ned Batchelder's comment here](http://stackoverflow.com/questions/7341005/python-conditional-variables-based-on-whether-nosetest-is-running) could do.
