### ISSUE TITLE
Add doc specifying the release procedure

### ISSUE THREAD

**Issue by xrotwang** [lingpy/lingpy#198]
There should be a doc `RELEASING.md`, specifying the release procedure, i.e. what has to be done to push a new LingPy release. This could be modelled after [the one for pyramid](https://github.com/Pylons/pyramid/blob/master/RELEASING.txt).

**Comment by LinguList** [comment]
Do we have a strategy on this? We could now describe that we plan: 

- releasing 2.6 as the next stable version with minor bugfixes
- releasing 2.7 with new code that is currently being prepared
- work on 3.0 as the new environment which is much more focused and no longer backwards-compatible
