### ISSUE TITLE
Don't hard-code LingPy version number

### ISSUE THREAD

**Issue by xrotwang** [lingpy/lingpy#203]
In various places hard-coded (and out-of-synch) LingPy version strings are used, e.g. `2.0` in [lexstat.py](https://github.com/lingpy/lingpy/blob/master/lingpy/compare/lexstat.py#L168), `2.2` in [settings.py](https://github.com/lingpy/lingpy/blob/master/lingpy/settings.py#L98). All these cases should instead use [`lingpy.__version__`](https://github.com/lingpy/lingpy/blob/master/lingpy/__init__.py#L25).

**Comment by LinguList** [comment]
I realized only last week or two weeks ago, that even the __version__
was not there in lingpy.__init__. And I only realized it, since I wanted
to use a howto-script that needed a version lingpy > something. Good
that you remind of this point...

**Comment by LinguList** [comment]
what is left with the old version are only the templates, in all other places this is fixed...
