### ISSUE TITLE
Refactoring: use itertools.combinations throughout

### ISSUE THREAD

**Issue by xrotwang** [lingpy/lingpy#206]
Currently, there are many instances in the codebase of code like

``` python
for i, a1 in enumerate(l):
    for j, a2 in enumerate(l):
        if i < j:
            # do things which require a1 and a2 but not i or j
```

All of these should be replaced with the equivalent

``` python
for a1, a2 in itertools.combinations(l, 2):
    # do things which require a1 and a2 but not i or j
```

or if `i` and `j` are required

``` python
for (i, a1), (j, a2) in itertools.combinations(enumerate(l), 2):
    # do things
```

Maybe `lingpy.util` should provide a shortcut, where a default of `2` for the length of subsequences is provided.

**Comment by xrotwang** [comment]
Sometimes, the pairs for indices `i <= j` are iterated over. This can be replaced with `itertools.combinations_with_replacement`.

**Comment by LinguList** [comment]
I think this is almost covered everywhere...
