### ISSUE TITLE
Refactoring: use dict comprehensions

### ISSUE THREAD

**Issue by xrotwang** [lingpy/lingpy#208]
[`dict` comprehensions](https://www.python.org/dev/peps/pep-0274/) are far more readable than their semantic equivalents and should be prefered. I.e. instead of

``` python
dict([(i, chr(65+i)) for i in range(4)])
```

LingPy code should use

``` python
{i : chr(65+i) for i in range(4)}
```

**Comment by LinguList** [comment]
I knew somewhere that these existed, but I thought it was a new py3 feature. Now I tested it and saw that it's really that simple. I'll immediately put that into my repertoire...

**Comment by xrotwang** [comment]
I think we do this in a couple of places now and hopefully won't fall back to the old variant. Replacing all of the `dict()`-style items systematically is probably not worth the pain.
