### ISSUE TITLE
Refactoring: use `defaultdict(list)`

### ISSUE THREAD

**Issue by xrotwang** [lingpy/lingpy#209]
In many place the idiom

``` python
    converted = {}
    for node in partition:
        try:
            converted[partition[node]] += [node]
        except KeyError:
            converted[partition[node]] = [node]
```

is found. This should be replaced by

``` python
    converted = defaultdict(list)
    for node in partition:
        converted[partition[node]].append(node)
```

because of the enhanced readability, but also because raising and catching exceptions is an expensive way of checking for `dict` membership.

**Comment by LinguList** [comment]
the only place where we fail to actually use this function is the cython code, where the double-i-loop is still used. I know that one could circumvent this with a while loop, but in tests I made in the past (only pure python, though), there was no recognizable performance difference in i-j-for-loops vs. i-j-while-loops, so the question is: should the respective positions in the cython-code also be modified in some way, or should we close this for the time being? 

Note also, that we can't import collections in cython code, at least I suspect that this will slow cython down...

**Comment by xrotwang** [comment]
I think we do this in a couple of places now and hopefully won't fall back to the old variant. Replacing all of the `try-except-KeyError`-style items systematically is probably not worth the pain.
