### ISSUE TITLE
Remove conditional imports of networkx

### ISSUE THREAD

**Issue by xrotwang** [lingpy/lingpy#220]
[`networkx`](https://github.com/lingpy/lingpy/blob/master/setup.py#L64) has been a requirement for quite some time, so all instances of [conditional imports](https://github.com/lingpy/lingpy/blob/master/lingpy/algorithm/clustering.py#L26-L30) should be removed.

**Comment by SimonGreenhill** [comment]
One drawback - networkX can be a pain to install, I've had real trouble with it under different compilers (CLANG?).

**Comment by LinguList** [comment]
Is it still that bad? We alrady have it as install requirement in setup.py for a while now, any problems with that in the past?
