### ISSUE TITLE
proposal for print-handling: change all pprint and print-instances with new util.print_stuff function

### ISSUE THREAD

**Issue by LinguList** [lingpy/lingpy#244]
I added a print_stuff function to util:

https://github.com/LinguList/lingpy/blob/a2b6a121f499e3ed75cc6ee7bffc94375b15bc1e/lingpy/util.py#L179

This function prints stuff unless loglevel prohibits this, and unless one passes the keyword "return_string". Then, it just returns the string.

I applied this to acd.py:

https://github.com/LinguList/lingpy/blob/a2b6a121f499e3ed75cc6ee7bffc94375b15bc1e/lingpy/evaluate/acd.py

and in the test, I receive 100%, since the print-statement is no longer used in the script itself, where we could not cover it, but in utils.

I do not know whether this is the preferred way to do it, but in this way, we could keep the print-functionality, using the keyword "pprint" for interactive sessions, where it is useful, while being able to completely ignore it otherwise. All that functions than need to offer is a pprint-keyword, and a statement that calls utils.print_stuff(string, return_string=return_string).

**Comment by xrotwang** [comment]
I think it is a good idea to factor more functionality like this out into small utility functions. But I have several issues with your current implementation:
- I don't like the name. `stuff`just sounds too much like "I couldn't think of a good name". maybe call it `output` or `print_output`? Actually, considering the points below, what the function may actually do, is format an object as string, and optionally printing it. So why not `as_string`?
- I would remove the `return_string` keyword, and just always return that string, and let the caller decide, what to do with it.
- The string object to be returned should be unicode, right? So `str` cannot be used for python 2.7.
- I would just pass the `pprint` flag as argument into `print_stuff` and append it as a condition to the `if` statement.

So:
```python
def as_string(obj, pprint=False):
    if get_level() <= logging.INFO and pprint:
        print(obj)
    return text_type(obj)
```

**Comment by xrotwang** [comment]
Probably better:
```python
def as_string(obj, pprint=False):
    obj = text_type(obj)
    if get_level() <= logging.INFO and pprint:
        print(obj)
    return obj
```

**Comment by LinguList** [comment]
cool! that makes it much easier to add the flag to the objects! Will modify accordingly and try to get rid of all remaining pprint without loglevel in the current verision...
