### ISSUE TITLE
Wrong link to MPI-SHH in documentation

### ISSUE THREAD

**Issue by LinguList** [lingpy/lingpy#251]
This should be shh.mpg.de, but it links to ssh.mpg.de

**Comment by xrotwang** [comment]
A classic!
Am 18.05.2016 13:15 schrieb "Johann-Mattis List" <notifications@github.com>:

**Comment by LinguList** [comment]
the bad thing is just that while this is easily fixed, I'll have to
upload the whole documentation, since sphinx creates static HTML. I
suggest that we do not give this immediate priority but wait to fix it
once we have some more things accumulated for some version 2.5.1...
