### ISSUE TITLE
user-documentation for cache and logging 

### ISSUE THREAD

**Issue by LinguList** [lingpy/lingpy#259]
we're obviously missing some nice user-documentation for logging and cache, as this often causes confusion. So to handle this, we need to either add a cookbook-howto or a more direct documentation to handle this. I guess, a cookbook-chapter would be the best, as this is not function-related but rather a procedure requiring a bit more information ("customizing lingpy").

**Comment by xrotwang** [comment]
Yes! I'll have a shot. Maybe jupyter notebooks are a good format for this?
Am 20.08.2016 11:54 schrieb "Johann-Mattis List" <notifications@github.com>:

**Comment by LinguList** [comment]
Yes, I think so! A larger question regarding user-documentation would be
where to store them. We could add a folder in lingpy/lingpy or
(preferred by me) use the current cookbook-repo on lingpy/cookbook. I
would then link all cookbook-entries to the lingpy.org
html-documentation created by sphinx in an extra-section called
"cookbook", which would give us some consistency in presenting the
recipes in new versions, while at the same time giving much freedom to
add new recipes whenever we feel necessary.
