### ISSUE TITLE
ZeroDivisionErrro in Alignments

### ISSUE THREAD

**Issue by LinguList** [lingpy/lingpy#261]
Test to replicate (shoud be added to tests):

``` python
>>> msa = Multiple(['tata', 'AB', 'C'))
>>> msa.prog_align()
```

The cython alignment code needs to be checked for strings with similarity=0 and two unrecognized characters. If this situation is met, it should either abort the alignmetn for this reason explicitly, or abort it in all cases where a string has self-similarity <= 0. One might consider adding a flag to allow for two behaviours, as it may be frustrating if because of one bad stirng the whole alignment strikes. But even better is just a more transparent check when loading the alignments class, which indicates danger if there are too many unrecognized characters.

**Comment by LinguList** [comment]
I am now thinking: do we still need this, given that the Multiple class is usually less exposed, as we tend to make alignments from within wordlists, where we have ways to check the data? The multiple._set_model function could add a test to raise an error easily. 

If we run this with a different keyword, it will only throw a warning:
```python
>>> msa = Multiple(['tata', 'AB', 'C'])
>>> msa.prog_align(classes=False)
```

**Comment by xrotwang** [comment]
I think the behaviour is ok, but a `ZeroDivisionError` isn't a particularly user- or developer-friendly way of relaying what's going on.

**Comment by LinguList** [comment]
so I think: adding a test if classes is set to true, raising a ValueError pointing to bad sound classes (it is when the sound class is completely unknown) seems to be the best way. Maybe, this could be general behavior. Suppose, you want to make an analysis, and you have a string that no algorithm can interpret, it is better to abandon. I already updated the method for testing strings, and this could probably just be used, or one could even make it more general, and if the function tokens2class contains only zeros, it should raise a ValueError, saying that the sequence is corrupted?

**Comment by xrotwang** [comment]
The earlier the better, I would say.

**Comment by LinguList** [comment]
and it's easiest. I'll try and have this already for my last PR for lingpy-2.6 (trying to get rid of some issues).
