### ISSUE TITLE
Empty return value of parse_gloss leads to KeyError further down.

### ISSUE THREAD

**Issue by Anaphory** [lingpy/lingpy#262]
I am using concepticon's `maplist.py` helper to map the 
[attached concept list](https://github.com/lingpy/lingpy/files/493339/maplist.txt), when I get the following error:
```
$ ipython -i maplist.py ~/databases/lexirumah-data/maplist.tsv 
/usr/lib/python3.5/site-packages/IPython/core/interactiveshell.py:712: UserWarning: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
  warn("Attempting to work in a virtualenv. If you encounter problems, please "
Python 3.5.2 (default, Jun 28 2016, 08:46:01) 
Type "copyright", "credits" or "license" for more information.

IPython 5.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
[i] Created temporary file from the current concepticon.
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/home/gereon/databases/concepticondata/helpers/maplist.py in <module>()
     80     compare_conceptlists('.temporary1.tsv', sys.argv[1], output='tsv',
     81             filename=sys.argv[1].replace('.tsv', '.mapped.tsv'), debug=True,
---> 82             gloss=gloss)
     83     print("[i] successfully mapped the lists.")
     84 

/home/gereon/aur/lingpy/lingpy/meaning/glosses.py in compare_conceptlists(list1, list2, output, match, filename, **keywords)
    387             defaults['match_quality'])]
    388         for i, line in enumerate(comp):
--> 389             for idx in line2idx[i]:
    390                 if idx in best:
    391                     data = best[idx]

KeyError: 12

In [1]: 
```
I would place the reason in [line 303](https://github.com/lingpy/lingpy/blob/master/lingpy/meaning/glosses.py#L303) ff, where

        gdata = parse_gloss(gloss, output='dict')
        for gdatum in gdata:
            gdatum['number'] = line[cnum]  # we won't need "enumerate" XXX
            C[idx] = gdatum
            try:
                line2idx[i] += [idx]
            except KeyError:
                line2idx[i] = [idx]
            idx += 1

means that if `parse_gloss()` returns an empty list, `line2idx[i]` is never set.

**Comment by Anaphory** [comment]
Now I see why that case is not considered: Every gloss *should* indeed have at least one part after being split on `;,/ or `. Yet somehow apparently some things don't.

**Comment by LinguList** [comment]
yes, error repeats with me. We should fire an error immediately in lingpy, saying that this gloss is not parseable, as it is erroneous (no gloss should end in a comma, dot, or the like), or catch it by adding the check already in parse_gloss and reducing the entry to one, from otherwise two.

Surprisingly, however, this seems already to be covered in the function, as 

```python

>>> parse_gloss('hand/')
[('hand', '', '', '', '', '', 'hand', ['hand'], 'hand')]
```
yields one entry as expected.

**Comment by LinguList** [comment]
There must be something else that triggers this behaviour.

**Comment by Anaphory** [comment]
I have a suggestion where the error comes from. Due to some legacy replacements, my example file above sometimes contains `\t` inside some other column, which means that the number of columns is odd because your manual parser does not ignore `\t` inside `""`, while the pandas parser I normally use has no problems with arbitrary text inside quotation marks. I still don't know why this leads to such results, but it's the best correlation I can find so far.

**Comment by Anaphory** [comment]
Observation one:
When I `s/\t /, /g`, I do indeed get “successfully mapped the list”. So that's what was unexpected.

Now as to why this leads to the observed behaviour in lingpy, I don't know yet, but I will for the moment instead use it and not puzzle about the internals.

**Comment by LinguList** [comment]
we'll leave this issue open, also to keep in mind as a warning, that we should not use hand-made arbitrary csv readers, as I originally did for lingpy, but robust libs that are already there. This is one of the future goals of lingpy to enhance IO, and to get rid of hand-made CSV. Here we see another example, why this was not a good idea back then in the olden times.

**Comment by LinguList** [comment]
I'll close this now, for the reason that we're currently working on an update in the concepticon api, which handles glossing. Glossing will thus in the future be kept out of lingpy, and another issue will be launched to remove the glosses.py from the library.
