### ISSUE TITLE
User-Input: Raise Error when Taxon-Names contain bad characters, like commata, etc.

### ISSUE THREAD

**Issue by Anaphory** [lingpy/lingpy#268]
I have commas in taxa names (the most easily available word list was our edictor input file, which abuses the douculect field)

```
>>> p.get_GLS()
||----------------------------------- GAIN-LOSS-MAPPING (w-1-1) -------------------------------------|
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/vol/home/kaipingga/Analysis/lingpy/lingpy/compare/phylogeny.py", line 1236, in get_GLS
    missing_data=keywords['missing_data']
  File "/vol/home/kaipingga/Analysis/lingpy/lingpy/compare/phylogeny.py", line 147, in get_gls
    scenarios[taxon] = [(statesD[taxon], {})]
KeyError: '1Pantar'
```

The key is probably actually `1Pantar, 1West – Timor-Alor-Pantar Sar-Adiabang`, but I assume at some point things are written to `csv` strings and read out again, which should not happen.

**Comment by LinguList** [comment]
You should generall NOT use bad taxon names with commas, as they won't display in Newick. But you may test this function, which should handle it:

* http://lingpy.org/reference/lingpy.basic.html#lingpy.basic.ops.clean_taxnames

**Comment by LinguList** [comment]
I think this is better treated as direct error output, if the wordlist does not conform to the standards. One could even automatically convert the taxon names and store the old names in another column, but I don't know whether we should take too much of the responsibility from the user.

**Comment by Anaphory** [comment]
No, raising an explicit error is fine.

**Comment by Anaphory** [comment]
(I mean, relying on Newick is an entirely different issue, which I don't think you should do unless you have to. But while you do, things that cannot be represented in there should throw an error.)

**Comment by LinguList** [comment]
well, if I start using XML or whatever other tree format, people will complain I don't support newick. Everybody uses Newick for tree representation, so I don't see a problem here. You can never please everybody. 

But yes, chekcing taxon names is definitely useful, and belongs to the list of things I anyway wanted to include there, namely more extensive checks and raising of errors before it is too late and people complain about strange results.

**Comment by Anaphory** [comment]
I don't mean not to *write out* newick when writing to files etc., but internally, while not writing to files (which is a thing I personally would ask for explicitly), I would find a Tree data type more convenient than handing around Newick strings.

**Comment by LinguList** [comment]
but that is already the case. There is a tree class, and you can access it, if you write:

```python
>>> print(p.tree.asciiArt())
```

That is a lingpy.base.tree.Tree class, forked from pycogent, but hopefully replaced by the python-newick class in the future.

**Comment by Anaphory** [comment]
Ah, okay, sounds good.

Hm, but at some point there must have been a step of parsing a `newick` string, or some other variant of string parsing beyond basically reading the word list, for `1Pantar, 1West – Timor-Alor-Pantar Sar-Adiabang` to be split at the comma to make `1Pantar` appear.

**Comment by LinguList** [comment]
yes, I see, this is the result of UPGMA, as these objects are
represented in newick. So you're right: there is a use of newick as a
format of tree-representation to pass it around. I wonder whether this
is a problem, as we also WANT to write newick in intermediate stages,
and whether the parsing of newick strings should maybe just handle
complex taxon names. Suppose, we solve (or maybe it's already solved!)
this in the python-newick library, the problem would not be there, but
we can still discuss to return python-internal tree-objects as
alternative to newick, although this requires to consider the
tree-construction algos, which don't create trees directly...

**Comment by Anaphory** [comment]
I have no problem restricting the space of valid tree node names! That's a things that could be done even for a `Tree` object being passed around, but then it would need to be explicit.

If everything internally operates on Newick-Strings instead of trees, it's not a bad format. But I doubt that's the case, such that parsing and re-writing newick strings sounds suboptimal. I have not looked at how much Newick strings are used vs. other Tree objects, so don't assume my opinion is fact-based or good.

**Comment by LinguList** [comment]
we just need to make sure language names are properly quoted when using UPGMA and the like. This is not done by now, but it is supported in the underlying newick library, and the new python-newick is even better at supporting this. So from there, it should be save.
