### ISSUE TITLE
plot_MLN cuts off margins of plot

### ISSUE THREAD

**Issue by Anaphory** [lingpy/lingpy#269]
Even though I'm not using my ridiculously long taxa names any more, `plot_MLN` cuts off `DOCULECT` names on the left and top of the tree, as shown in the attached file.

My workaround is to export to `'svg'` and then move the output to fit inside the page.

If you think this might be related to `networkx` or `matplotlib` versions, I can try with a different one.
![tap-aligned tsv](https://cloud.githubusercontent.com/assets/1579723/19561300/64e1178c-96d8-11e6-8fed-72f22c56af5a.png)

**Comment by LinguList** [comment]
this is a matplotlib problem. A general problem, and you can handle it with undocumented parameters, which are also undocumented in matplotlib (yes, most of the tweaks in matplotlib I know only from stackoverflow).

Please look at this howto script, that plots a good figure with MLN:

* https://gist.github.com/LinguList/7481097#file-chinesedialecthistory-py-L63

You see, there is also a "figsize optima" parameter, that calculates optimal figsize, but it's impossible to foresee it exactly. The important features to tweak it are either an explicit figsize (tuple: figsize=(20, 10), or to use left and top (following matplotlib style, so left=0.1 means margin of 0.1 from the left, and top=0.9 means figure ends at 0.9 on top.

BUT: I don't use any of this anymore, as I realized that loading a pdf-graphic into inkscape with just allow to perfectly crop it. So I decided that before I start adding yet another tweak for matplotlib, which won't work for all data, I'll just leave it as is, and I think, I'll even consider to discard most of the current tweaks in an update on MLNs, as it is just too much work for things that just fail all on every new dataset...

**Comment by LinguList** [comment]
I'll leave this thread open, but I'll leave it for the MLN documentation milestone to add this information that the plot needs to be cropped with some external software. Just to make this clear: the pdf is intact, it's just that the taxon names are cropped, you'll see all the image when loading it into Adobe-pro or inkscape.

**Comment by Anaphory** [comment]
Makes sense, and is very much what I assumed. Given that it's down to `matplotlib` failing, I'm also very fine with just shifting the blame instead of hackish workarounds.
