### ISSUE TITLE
Word list written by lingpy cannot be read back in

### ISSUE THREAD

**Issue by Anaphory** [lingpy/lingpy#270]
The cognate autocoding file template @LinguList gave me worked fine for quite some time, but some recent changes (which I haven't pinned down yet) have broken it in an unexpected way: I construct a `WordList` object `wl`, which is then written to a file and read back in.

```
wl.output('tsv', filename='tap-cleaned', subset=True, rows=dict(
    ID = 'not in '+str(deletes)))
print('wrote data to file')

with open('errors.log', 'w') as f:
    f.write('\n'.join(log))

with open('segments.log', 'w') as f:
    for a, b in sorted(segments.items(), key=lambda x: x[1]):
        f.write('{0}\t{1}\n'.format(a, b))

# compute cognates
lex = LexStat('tap-cleaned.tsv', segments='segments')
```

After me tweaking the underlying raw tsv files `wl` is constructed from, LingPy is now refusing to parse the file back in.

```
[i] Wordlist has 600 languages and 643 concepts in 29708 entries.
2016-10-26 15:12:43,607 [INFO] Data has been written to file <tap-cleaned.tsv>.
wrote data to file
Traceback (most recent call last):
  File "cognates.py", line 88, in <module>
    lex = LexStat('tap-cleaned.tsv', segments='segments')
  File "/vol/home/kaipingga/Analysis/lingpy/lingpy/compare/lexstat.py", line 359, in __init__
    for idx in self.get_list(col=taxon, flat=True):
  File "/vol/home/kaipingga/Analysis/lingpy/lingpy/basic/wordlist.py", line 394, in get_list
    raise ValueError("Neither rows nor columns are selected!")
ValueError: Neither rows nor columns are selected!
```

(I am also surprised that it reports 600 languages, I expect about 40.)

The first few lines of `tap-cleaned.tvs` look like this:

```
# Wordlist

# DATA
ID  CONCEPT_ID  CONCEPT DOCULECT_ID DOCULECT    FAMILY  REGION  VALUE   COMMENT ALIGNMENT   COGNATE_SET SOURCE  LOAN    REFERENCE   ORIGINAL_FILE   SEGMENTS
#
9154    82.0    (thatch) roof   sout2896-kalik  Lembata-Kalikasa    Austronesian    8Lembata    naˈkər    nan nan nan nan     W1a; W1a    datasets/lhhf2015clembatakalikasa2015511wordlist.tsv    n a ˈk ə r
9155    82.0    (thatch) roof   sout2896-kalik  Lembata-Kalikasa    Austronesian    8Lembata    uˈvuŋ uwung actually means ridge of a roof …    nan nan nan     W1a; W1a    datasets/lhhf2015clembatakalikasa2015511wordlist.tsv    u ˈv u ŋ
#
9292    207.0   1pl excl    sout2896-kalik  Lembata-Kalikasa    Austronesian    8Lembata    kam proclitic   nan nan nan     W1a datasets/lhhf2015clembatakalikasa2015511wordlist.tsv    k a m
9293    207.0   1pl excl    sout2896-kalik  Lembata-Kalikasa    Austronesian    8Lembata    ˈkame  nan nan nan nan     W1a datasets/lhhf2015clembatakalikasa2015511wordlist.tsv    ˈk a m e
#
9294    208.0   1pl incl    sout2896-kalik  Lembata-Kalikasa    Austronesian    8Lembata    ˈtite  nan nan nan nan     W1a datasets/lhhf2015clembatakalikasa2015511wordlist.tsv    ˈt i t e
#
9285    203.0   1sg sout2896-kalik  Lembata-Kalikasa    Austronesian    8Lembata    ɡo short form  nan nan nan     W1a; W1a; ? datasets/lhhf2015clembatakalikasa2015511wordlist.tsv    ɡ o
9286    203.0   1sg sout2896-kalik  Lembata-Kalikasa    Austronesian    8Lembata    ɡone   nan nan nan nan     W1a; W1a; ? datasets/lhhf2015clembatakalikasa2015511wordlist.tsv    ɡ o n e
#
9295    209.0   2pl sout2896-kalik  Lembata-Kalikasa    Austronesian    8Lembata    ˈmio   nan nan nan nan     W1a datasets/lhhf2015clembatakalikasa2015511wordlist.tsv    ˈm i o
#
9287    204.0   2sg (informal)  sout2896-kalik  Lembata-Kalikasa    Austronesian    8Lembata    mo  short form  nan nan nan     W1a; W1a    datasets/lhhf2015clembatakalikasa2015511wordlist.tsv    m o
9
```

It appears that the `COGNATE_SET` column and all further ones have gone missing. I would not be surprised if that was related to this issue, because I changed the content of that particular column.

**Comment by Anaphory** [comment]
Note: This is not about fixing that particular file, which got cleanly generated after I fixed something in the files it comes from. This is about the observation that a WL file written by LingPy could not be read again, which *may* be because I didn't understand what certain parameters do, but *may* also be unexpected to you.

**Comment by LinguList** [comment]
ValueError: Neither rows nor columns are selected!

This is the point. You're header is apparently missing entries which are
"CONCEPT" and "LANGUAGE" (or doculect, gloss, etc.). The error is
designed for this specific problem.

**Comment by LinguList** [comment]
The defaults are actually documented: see [here](http://lingpy.org/tutorial/lingpy.basic.wordlist.html) and [here](http://lingpy.org/tutorial/datastructures.html), with two pdf tutorials (based on ipythonnb). Default for each wordlist is to assign col and row, col, usually pointing to a "doculect", and row, usually pointing to a "concept" column. Without any of those, you need to re-specify what is your col and your row, but I hope you'll find some answers already by looking at the tutorials, as I have tried to explain the philosophy there.

**Comment by LinguList** [comment]
I'm not sure still what was going on here, but I think we can say that the task should be that loading a wordlist needs more checking for basic things:

- [ ] do we find the "col"
- [ ] do we find the "row"
- [ ] do we have (accidentally) identical column headers? [a problem in some cases]

Anything more?

**Comment by Anaphory** [comment]
I'm not sure either. I thought it might be something with varying numbers of columns, but normally that is cleanly reported.

**Comment by LinguList** [comment]
BTW, I just gave you, @Anaphory, access right, so if possible, use some of the labels for these reports, so that we can handle them more easiily in the future.

**Comment by LinguList** [comment]
Unfortunately, regarding column number variation, there cannot be any tolerance, as I had serious problems in the past, before I added the check. However, having a system as github has, that points to an error and even tries to guess what the error is, would be cool, although I'm reluctant to spend too much time on that for the moment. I'm not particularly fond of the current error message, but it's at least consistent.

**Comment by Anaphory** [comment]
Oh, yes! I think Pandas just flat out refuses to parse a file with inconsistent columns and throws some Exception for that. Giving a warning is very lenient and convenient by comparison!

I only thought something like that was going on because when looking through the files, I noticed that some of them had inconsistent columns, which my other script cleaned up, after which the automatic aligmnent worked fine. But the files were quite messy overall, so it probably wasn't that.

**Comment by LinguList** [comment]
On a little side note: use the keyword "prettify=False" when writing with Wordlist.output(), because this will strip of the #Wordlist stuff, and as a result, you can easily check files with spreadsheet readers, as I now do usually, as it is much more convenient to detect bad columns, and the like (detect, not correct, as this can be dangerous if one has some strange non-unicode format or automatic number-converson).

**Comment by LinguList** [comment]
I'll close this now, I think, for most of the parts it should be okay, we could still reifne the "neither rows nor cols are selected"-error, but if people actually read the wordlist documentation, it should be clear that his is the key of the Wordlist.class, that we have a column and a row in our file (col="doculect", row="concept"). This is documented all over the place, e.g., here: http://lingpy.github.io/tutorial/lingpy.basic.wordlist.html
