### ISSUE TITLE
Default parameter values are not documented

### ISSUE THREAD

**Issue by Anaphory** [lingpy/lingpy#271]
I just tried to see whether my automated cognate-coder could be convinced to keep manual alignmnents intact. That is, I would like an alignment that is compatible with and does not change the alignment values already specified, but will freely invent something new for the empty cells. I had hoped that understanding the parameters for iterated refinement might help me figure it out. (Idea: generate an alignment for everything, overwrite it where it does not match the originally specified alignment, and then refine?)

Currently, the line reads `alm.align(override=True, alignment='alignment')`. `alm` is a `lingpy.Alignments==lingpy.align.sca.Alignments` object. The [documentation](http://lingpy.org/reference/lingpy.align.html#lingpy.align.sca.Alignments.align) lists neither an `override` nor an `alignment` keyword option, should the method throw an error in this case?

The documentation does not list the default values for `mode` and `model`.

I also don't fully grasp how various options interact, but then again I have not studied the articles underlying the method at all and can only hope that the default values chosen are reasonable.

**Comment by LinguList** [comment]
I don't really see the problem, but it's simply because I'd need a toy example: could you zip a small fraction of your data along with your script, so that I can review and comment the commands? The docu, yes, dose not document all params, but for alignments, for example, you can keep n columns storing different alignments, but you can only work on one of them at one time, which is reasonable, I guess, although more would be theoretically possible, as alignments are stored in a dict, so you have wl.msa['alm1'], theoretically also wl.msa['alm2'], but I don't remember how I thought they could be triggered (maybe loading alm1, but manipulating alm2). You are probably uncovering some serious things we should change in the future here, but I need the toy example, to see exactly what you mean.
Keyword "alignment" should be documented, by the way, at least in the __init__ function, but we should check...

**Comment by LinguList** [comment]
BTW:

**Comment by Anaphory** [comment]
> a small fraction of your data along with your script, so that I can review and comment the commands?

You should still have access to my `lexirumah-data` repo, it just lives in there and reads the files in `datasets/`.

> Keyword "alignment" should be documented, by the way, at least in the `__init__` function, but we should check...

Ah. Makes sense. Should `align` accept it, or did it land in that call by accident? `override` is definitely ignored/undefined, because I'm asked everytime whether I want to override the existing column

> takes some time to understand what lingpy does […] I hope you also understand that I can't foresee all specific demands users can have

Ah, sorry.

I did not mean that the docs should explain the processes it detail – I meant precisely that it's *my* duty to understand what it does/should do from at least skimming the referenced articles, and if I then *still* have questions how to represent what I find there in the method call, *then* I can raise an issue about it, and I have done none of this so I am not saying anything about whether I find the documentation of those other parameters sufficient or not.

--------------------------------------------

To rephrase: I found the following issue when I wanted to look up whether `override` of `Alignment.align` has a value that means “Only if it is not set yet”:

`override` and `alignment` parameters are not documented in `Alignment.align` (and probably undefined anyway) – should the method notice that and raise an `Exception`?

The parameters `mode` and `model` are optional, but their default values are not given in the documentation.

**Comment by LinguList** [comment]
Yep, so let's summarize:

- [ ] mode and model (both documented in full in the Multiple alignment function, which is a standalone), should be documented in Alignments.align
- [ ] override should be documented as well (as nobody knows what it does, see below)
- [ ] maybe think of refining the error code for "row and column" are not specified, or something similar to make #270 more explicit

As to the override: This should be checked in full, as the overwriting of content in a column is something that is a bit problematic to handle, or problematically handled right now. The keyword stems, FYI, from the Wordlist.add_entries('source', 'target', function) function, which I use a lot, and it is used to check whether a given column should be overwritten or not. But it is not always working as it should, I realized, and the interactive mode "do you want to override?" is probably also not the best (although I'm not sure myself).

**Comment by Anaphory** [comment]
Ah, it's passed through? Okay, that makes sense.

- [ ] Remark that `Alignments.align` passes other keyword arguments through to other methods in its docstring

**Comment by LinguList** [comment]
I'm closing these now, as it is too fuzzy to go after all of those issues. We'll see for lingpy2.7 and lingpy3 to work on documentation.
