### ISSUE TITLE
PhyBo.__init__ ignores bad tree

### ISSUE THREAD

**Issue by Anaphory** [lingpy/lingpy#281]
Trying to use https://gist.github.com/LinguList/7481097 as a template for creating a MLN with a given tree, I noticed that 

    phy = PhyBo('basic.qlc', degree=180, change=lambda x:3*x**1.2, tree="test.tre")

will fail when the tree cannot be parsed, but if the tree in `test.tre` is valid newick (my test case was `()`), it will run through and fail at a later

     tree.getTipNames()

with

    AttributeError: 'NoneType' object has no attribute 'getTipNames'

Given how much pre-processing we usually do, I find this surprising, and consider it a bug to not check that the tree matches the data file (or maybe has non-empty intersection, if we expect people to feed in larger or smaller trees than implied by the set of doculects in the data file, but that should be made explicit and otherwise fail).

This is not worth getting a separate fix now, but we should keep it in mind when continuning the python-newick integration.

**Comment by Anaphory** [comment]
Actually, the other part of the problem, which makes this confusing to debug, is that `lowestCommonAncestor` is permitted to return `None` instead of either an empty tree or raising an exception: Even if the tree is (somewhat) fine, the line

    tree = tree.lowestCommonAncestor([t for t in taxa if statesD[t] == 1])

may feed no taxa into the method (I picked three random languages for testing, and I wouldn't be surprised if their PAPs are bad), but then it's the inconspicuous `getTipNames()` which dies as shown above, even though at the start of the method, `tree` is fine.

**Comment by xrotwang** [comment]
It would be cool if you could turn your trials into tests in https://github.com/lingpy/lingpy/blob/master/lingpy/tests/compare/test_phylogeny.py
Is this doable?

**Comment by LinguList** [comment]
I'll close all phybo-related issues, as I consider that this method would either need to be made a standalone after lingpy3, or to be buried alltogether, given that it uses really bad ways to compute the sankoff parsimony. I hope we can include sankoff parsimony (as it is particularly useful and not implemented on a flexible level for linguistic needs) in lingpy 2.7, but Phybo is lowest in my priority list.
