### ISSUE TITLE
Use of col for PhyBo.__init__

### ISSUE THREAD

**Issue by Anaphory** [lingpy/lingpy#282]
Instead of the `DOCULECT` column, I want to use the `DOCULECT_ID` in a tsv file to represent one of the *dimension*s of a word list.

From the documentation (which I find still confusing on this matter, but you know that) I thought I would do this by specifying `col` in the `Wordlist` (or, in this case `PhyBo`) constructutor. However, this has no effect, and even when putting absolute nonsense in the `col` parameter, it is just ignored.

 - [ ] Where in the documentation should I find how to specify the column of a TSV file representing the language ID?
 - [ ] Where in the documentation *do* I find that information?
 - [ ] What does the `col` parameter actually do?
 - [ ] Could the polymorphism of `Wordlist.__init__`, accepting dicts as well as different file types with different switches applying to them, be split into some `@classmethod`s, such as `.from_dict()`, `.parse_qlc()`* and `.parse_tsv()` in the future?

*) I am sorry, I still haven't seen what qlc actually is. Is it one specific derivative of tsv (similar to cldf, but with comments and different column names) or something entirely different?

**Comment by Anaphory** [comment]
Oh, Boo!

https://github.com/lingpy/lingpy/blob/master/lingpy/compare/phylogeny.py#L313:

            Wordlist.__init__(self, dataset, row='concept', col='doculect')

No wonder me specifying `col` in the `PhyBo` constructor has no effect!

**Comment by LinguList** [comment]
okay, so just rename the column name pragmatically in the file for the moment. 

Then, looking at this line here: https://github.com/lingpy/lingpy/blob/master/lingpy/compare/phylogeny.py#L313

You see that the col/row are fixed. You can easily change that behaviour by setting a default, right? I mean, it's just changing one line, so you can test that in your code and submit a PR if it works.

And regarding splitting into classmethods its the same: ideally, you propose something that passes the tests, as I won't have time this year to work on this, and in line of priorities, I would put rate this low, as there are more urgent things to be done, I think.

As to PhyBo: the method needs to be rebuild from scratch, so consider also a pragmatic attitude towards it for the moment, and do not expect too many things to be changed in the actual version.

As to the col-parameter, check [this](http://lingpy.org/tutorial/datastructures.html) tutorial.

**Comment by LinguList** [comment]
Yep, no wonder, and consequently, it is also not documented that you can change names for "concept" and "doculects". But it should be a minor thing for testing to change "XXX" in your csv file to "concept".

**Comment by Anaphory** [comment]
Yes, it's fine for now. I just assumed (I should not assume things!) that the unspecified **keywords would be passed down to the `Wordlist` constructor.

**Comment by LinguList** [comment]
If you change that line, you need to change down phybo all kinds of things, as it was designed for very specific input data. I changed behavior in lexstat recently, now handling these parameters more explicitly, but given that I consider phybo to be ready to be replaced with some backwards-incompatible new version, I don't think it's worth the pain of regularizing all of this.

BTW: you may consider looking into an additional tool that uses maximum likelihood for gain-loss mapping:

http://gloome.tau.ac.il/

You won't have the output of linked trees, but it has the advantage of being stochastic, and you might even compare it against the phybo-stuff.

**Comment by Anaphory** [comment]
I'll look at Gloome in the future, for the moment I'm preferring pretty pictures.

**Comment by LinguList** [comment]
I guess that's one of the advantages of MLN, but also the big pain in maintaining the params.

**Comment by LinguList** [comment]
closing this now, as it seems unfeasible, given that MLN should generally refactored or remade.
