### ISSUE TITLE
convenience function for iteration in wordlists

### ISSUE THREAD

**Issue by LinguList** [lingpy/lingpy#285]
there is an incredibly redundant way in which the iteration across word lists is done at the moment:

```python
>>> for k in wordlist:
            print(wordlist[k, 'columnname'])
```
A simple function, which we could call, say, "list", would do the same, but could be called in one line:

```python
>>> for k, doculect, concept in wordlist.list('doculect', 'concept'):
       print(doculect, concept)
```
So the function would just be called as `wordlist.list(*colunmnames)` and it would return the key and the column content which was specified. This would spare a lot of code also inside existing lingpy scripts. 

An alternative function could return a dictionary, or an ordered dict. 

This could even be used as a basic to prepare the shift to a more intuitive handling of the wordlist class, which so far seems to confuse the users more than that it helps.

Questions would be: calling the two functions, one returning a list along with the ID, and one returning the ID and a dictionary, just `wordlist.list(*values)`, and `wordlist.dict(*values)`, or are there more intuitive names, or a generic function `wordlist.iter(*values, data=[dict|list])`?

**Comment by xrotwang** [comment]
I guess that's similar to the difference python's `for item in list` makes in comparison with `for (i = 0; i < list.length; i++)`. But from my perspective the root of this problem lies in the fact that wordlists are not modelled as lists, but are (as far as I can see for no stringent reason) turned into `dict`s. I think a wordlist should ideally inherit from `list` - or [alternatively](https://en.wikipedia.org/wiki/Composition_over_inheritance) contain a list of rows exposed via its `__iter__` method.
Tacking list-like behaviour onto wordlist without changing its core implementation would just increase the confusion, I think.

**Comment by xrotwang** [comment]
To follow up: I think the most "natural" data structure for a wordlist would be a `list` of `OrderedDict`s. Turning this into a `dict` based on any column is a one-liner:
```python
{row['ID']: row for row in wordlist}
```
Maybe we could add a[ `visit` method](https://en.wikipedia.org/wiki/Visitor_pattern), which accepts a callable as argument which is called for each item in the list. I found this to be good way to implement stuff like in-place modification of lists without much boilerplate.

**Comment by LinguList** [comment]
Well, the reason why it is a dict is that we want to call one item by its ID, and since IDs were not necessarily following enumeration in a file. Here, turning all items into a dict upon each call would surely not be very efficient. Yet on the other hand, as wordlists are stable and do not allow to add more rows, all indices are anyway stored in the numpy.array which I would much like to get rid of.

But in general, I guess the dict character saves time, as we often need to call items by index (like the items with the same concept). At the moment the dictionary is inconsequent, as far as IDs are integers, but that we need a key-value structure here seems inevitable. As to the ordered dict instead of the list as value, I agree that this would be the logical structure, and while I discarded it for speed reasons, it may well be that I had some error elsewhere, and that the slow iteration was due to something else I did not realize.

So apart from the fact that I agree that the general wordlist construction should be (at some time) modified, having above-mentioned behaviour would certainly be useful in general for wordlists constructs. And if I understand the visitor-method idea correctly, this could be a separate function instead of a class-method. As the function that triggers the behaviour I want for the wordlist enumeration is anyway a three-liner, I could as well place it in basic.ops for the moment instead of making it a class method. In any way, I think the general idea of this function is something that would be extremely frequently used inside of the major code for cognate detection and could serve as a first step towards refactoring the wordlist-class in general.

```python
def iter_rows(wordlist, *values):
    for idx in wordlist:
        yield [idx]+[wordlist[k, value] for value in values]
```

vs.


```python
class Wordlist():
    def iter_rows(self, *values):
        for idx in self:
            yield [idx]+[self[k, value] for value in values]
```

**Comment by xrotwang** [comment]
Yes, I think it's a good idea to have this a separate standalone function.
And you are right in that this could help with transition to a simpler
wordlist class.
As far as I know, OrderedDicts only cost time upon creation, not when
iterating over the values, but we could benchmark this. If we know
wordlists cannot be appended to, this should be reflected, in fact enforced
by the data structure, so probably containment of a list or dict is the
better option than inheritance. Let's start putting together a design spec
for this main object in lingpy.
Am 19.11.2016 10:20 schrieb "Johann-Mattis List" <notifications@github.com>:
