### ISSUE TITLE
add a cldf reader (and ideally also writer)

### ISSUE THREAD

**Issue by LinguList** [lingpy/lingpy#307]
This will help us to:

1. read in cldf data and analyse it (should be trivial as clldutils is already a dependency, and pycldf could also be added)
2. convert data after lingpy treatment back to cldf
3. provide some additional manipulations (e.g., calculate distance data, etc.)

**Comment by LinguList** [comment]
Here's a nice example on how this could look like:

* https://github.com/lessersunda/lexirumah-data/blob/with_lexi_data/pylexirumah/lingpycldf.py

**Comment by Anaphory** [comment]
Note that the linked script is metadata-unaware and meant as a minimal stand-alone script to make CLDF files workable in Edictor.

**Comment by Anaphory** [comment]
Additional manipulations don't belong in the CLDF reader.

Instead, write pluggable CLDF reader and writer for objects which can then be used by the normal (or future normal, once LingPy is not assuming that everything is read from a file and written to a file) LingPy functions and modules.

**Comment by LinguList** [comment]
I am optimistic that expanding this to be metadata-aware is quite straightforward, thanks to the pycldf-api, which is light enough to be a dependency for lingpy.

**Comment by Anaphory** [comment]
For lingpy, I wouldn't use my script, I would write a clean reader and a clean writer that generate/work with LingPy objects.

After that, it's simple enough to write a CLI script that does the conversion, but if you want cldf reading in LingPy, that CLI script is a byproduct, not the first step.
