### ISSUE TITLE
add splitstree to nexus export

### ISSUE THREAD

**Issue by LinguList** [lingpy/lingpy#328]
splitstree cannot read mrbayes nexus or beast nexus, so we need to add splitstree nexus, for reasons of consistency

**Comment by SimonGreenhill** [comment]
I'll take this. I know what splitstree is breaking on.

**Comment by LinguList** [comment]
It's a nightmare, with nexus, isn't it? I mean: luckily, we can circumvent with help of the distances and direct phylip export, which is probably even better than computing distances from binarised cognate sets, but the fact that they all complain if you call characters 'standard', or 'binary', etc. is just "so sad", as presidents would say.

**Comment by SimonGreenhill** [comment]
Oops, sorry -- I pushed to master, it's done in e320b1aac22757b43729684d7a8e1445761f524b
