### ISSUE TITLE
Export nexus for TraitLab

### ISSUE THREAD

**Issue by LinguList** [lingpy/lingpy#330]
Valentin Thouzeau informed me about necessary conversions:

> It was the file without the concepts, and I had to deleat the words without variability (n° 1 and n° 234) to run BEAST. I read the data with R using the function read.nexus.data from the package ape, then I deleated these words, then I wrote the updated dataset using the function write.nexus.data.

**Comment by LinguList** [comment]
Comment by Guido Grimm on the difficulty of turning one nexus into others:

> Actually, that is very simple these days. Do you know Mesquite? It can read in pretty much any format and spill out the matrix as "simple NEXUS" (which is a clean NEXUS accepted by all NEXUS-compatible programmes including SplitsTree), also have an export for MrBayes, which will add the necessary lines, and "extended" Phylip, the basic format used for many other programmes, extended because the Mesquite PHYLIP export can have more than the original 6-character names. 

It means, we could just add a statement, stick to BEAST and MrBayes export in the current version (one bug in MB export, though) and point user to Mesquite.

**Comment by SimonGreenhill** [comment]
Ugh, Traitlab should handle constant sites -- that should be fixed upstream! But I can easily hook this into the nexus exporter if you want.

**Comment by LinguList** [comment]
Suppose, we do the lingpy-2.6.3 by Tuesday, if it is not too much to add this by then, we could include it in 2.6.3, but otherwise, it can safely wait until later...

**Comment by SimonGreenhill** [comment]
Closing this -- can be reopened if the format isn't correct.
