### ISSUE TITLE
Fix clldutils dependency

### ISSUE THREAD

**Issue by xrotwang** [lingpy/lingpy#333]
I just released a backwards incompatible version 2.0 of `clldutils`. Thus, the [dependency in lingy](https://github.com/lingpy/lingpy/blob/e4e87499a5ea3be6e1fa83e59e2973b9bf0b3700/requirements.txt#L4) must be either pinned to 1.14, or set to a [compatible release](https://www.python.org/dev/peps/pep-0440/#compatible-release), i.e. `~=1.6`.

**Comment by xrotwang** [comment]
Sorry, to introduce this bug somewhat deliberately. But switching to compatible release specifiers for dependencies may make sense in general.

**Comment by LinguList** [comment]
No problem, I saw it coming.

**Comment by xrotwang** [comment]
Yeah, the bad part is that this kind of thing leads to horrible end user experience. You could basically install lingpy without a problem yesterday, and doing the exactly same thing today will break ...
Anyway, other than running the lingpy tests everything should be back to normal with clldutils 2.0.1.

**Comment by LinguList** [comment]
I assume for the time being that users won't install lingpy over Christmas and new year. A question though remains: this means we'll have to do the same bugfix for concepticon, right? We don't have a release, but we'll have to add csvw as an additional dependency, right?

**Comment by xrotwang** [comment]
Yes, we should.

Am 22.12.2017 15:17 schrieb "Johann-Mattis List" <notifications@github.com>:

I assume for the time being that users won't install lingpy over Christmas
and new year. A question though remains: this means we'll have to do the
same bugfix for concepticon, right? We don't have a release, but we'll have
to add csvw as an additional dependency, right?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/lingpy/lingpy/issues/333#issuecomment-353606404>, or mute
the thread
