### ISSUE TITLE
RST rendering for PyPi

### ISSUE THREAD

**Issue by LinguList** [lingpy/lingpy#344]
If there's no README.rst, it looks ugly on PyPi. Thanks to Pandoc, this is easy now.

```shell
$ pandoc --from=markdown --to=rst --output=README.rst README.md
```

But it means we should do it before each new release and before pushing data to PyPi.

**Comment by LinguList** [comment]
Here's how it looks with pandoc: https://github.com/LinguList/lingpy/blob/master/README.rst

**Comment by SimonGreenhill** [comment]
Not any more! https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi

**Comment by LinguList** [comment]
It still looks ugly with current lingpy, though: https://pypi.python.org/pypi/lingpy

**Comment by LinguList** [comment]
I don't really understand, but even with the RST version, it doesn't work. Or am I not understanding anything on how to trigger the description of the package in pypi? Unfortunately, one cannot longer do it manually...
