### ISSUE TITLE
ipa2tokens() fails ungracefully on potentially bad input

### ISSUE THREAD

**Issue by tresoldi** [lingpy/lingpy#365]
I have been working with some data from Heggarty's [sound comparisons](http://www.soundcomparisons.com/). `ipa2tokens()` is failing in some of the transcriptions, as they have  combining diacritical markers in initial position (an example is the transcription for Nigerian Igbo's English "what", as below):

```python
In [1]: import lingpy

In [2]: test = "͡wɔ̞ˑt"

In [3]: test.encode("unicode_escape")
Out[3]: b'\\u0361w\\u0254\\u031e\\u02d1t'

In [4]: lingpy.ipa2tokens(test)
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-4-7a6bff6aa96d> in <module>()
----> 1 lingpy.ipa2tokens(test)

~/src/lingpy/lingpy/sequence/sound_classes.py in ipa2tokens(istring, **keywords)
    150         # check for combiners next
    151         elif char in kw['combiners']:
--> 152             out[-1] += char
    153             merge = True
    154 

IndexError: list index out of range
```

Both considering this input poorly formed or special enough for having lingpy intentionally failing are good positions -- this test case itself seems wrong, and should be `w\u0361\u0254\u031e\u02d1t`. In such cases, however, it would be better to test for initial "combiners" and explicitly refuse them (or we can just accept them, either as standalone tokens or appending a dummy base glyph -- maybe the empty set? -- as it is not up to `ipa2tokens()` to perform data cleansing).

**Comment by LinguList** [comment]
Agreed. Maybe, the standalone thing is the best, if it's not too difficult to add it to the code (okay, in worst case, one more if-loop plus an additional test...).

**Comment by tresoldi** [comment]
I think I would opt for just having it fail more gracefully. It is hard to conceive a situation where you'd actually need a combiner in the first position, plus it can hardly improve alignment and cognate detection (not to mention that it is hard to spot it without escaping the string),

Still, no matter the solution, we do need one more if-statement in `ipa2tokens()` and one more test. I'll take care of it, we can always move back to non accepting it.

**Comment by tresoldi** [comment]
@chrzyki this is not urgent, should I wait for you to finish implementing the new test framework?

**Comment by xrotwang** [comment]
@tresoldi I guess stuff like this would also be good (edge) test cases for clts, right?

**Comment by tresoldi** [comment]
@xrotwang I guess it would, it might even be a good idea to run some random/fuzzy testing to see if we catch something else.

In this particular case, everything is fine: if I split the tokens manually, clts correctly maps the initial combiner to an `UnknownSound`; if I place it after the `w`, the transcription results as intended (or, at least, as it is *my* intention). This is after all the expected behaviour, as clts' transcription systems are not supposed to receive phonetic sequences, but tokens. Still, good to see it is handling it without throwing an unintended exception.

**Comment by chrzyki** [comment]
@tresoldi Thanks for asking; no, that's quite alright. Go ahead and fix/change, I'll redo my PR/branch accordingly. :)

**Comment by LinguList** [comment]
@tresoldi, with your PR, this is handled, right? If so, could you close this issue?
