### ISSUE TITLE
Converting from and to CLDF: Any reason not to use pycldf?

### ISSUE THREAD

**Issue by Anaphory** [lingpy/lingpy#369]
The implementation of `from_cldf` (which looks very much like a class method, all it needs doing is to make `to` its first parameter and put in the right place with the right decorator, by the way) states https://github.com/lingpy/lingpy/blob/a64bc8629006dc31b266bfb4bba6a4bb557b3007/lingpy/basic/wordlist.py#L1096

We could supply a lot of that flexibility by using `pycldf`, is there any reason not to?
My database has some non-standard column names (eg. `Lect_ID` instead of `Language_ID`), so I essentially have code doing something like this already (using LingPy for cognate coding and alignment) and could adapt it quite easily if you want me to. My code would also check for a `cognatesetReference` column in both `FormTable` and `CognatesetTable`.

**Comment by Anaphory** [comment]
I have noticed #367, which would need to be taken into account for any change of `from_cldf`, but I don't fully understand it yet.

**Comment by LinguList** [comment]
> We could supply a lot of that flexibility by using pycldf, is there any reason not to? 
If you have a concrete idea of enhancing, I'd be very pleased!
as to 
> I have noticed #367, which would need to be taken into account for any change of from_cldf, but I don't fully understand it yet.
we have in edictor a very strict format, also in lingpy's partial cognate detection, which, however was decided to be represented differently in cldf and is currently not converted by the function.

**Comment by Anaphory** [comment]
Excellent! I'll have a look.

**Comment by Anaphory** [comment]
I lifted functionality I had used in Beastling before, adapting to the LingPy case.

Check https://github.com/Anaphory/lingpy/commit/daf7a649eaff2e95650f559721a9177dbb001ed7 – tell me about any improvements you deem necessary.

So far I have only tested this by running

    >>> lingpy.Wordlist.from_cldf("lexirumah-data/cldf/Wordlist-metadata.json", col="lect_id", row="concept_id")
    <lingpy.basic.wordlist.Wordlist object at 0x7fde9f26ef98>

and seeing no raised Exception.

**Comment by Anaphory** [comment]
What policy should this use to rename columns? Let's assume

    dataset["CognateTable", "cognatesetReference"].name == "CognateClass"

Then the current code would import this with the name `cognate_cognateclass` and LingPy's default for a column like that is `cogid`, but it might also be partial cognates if I remember the standard correctly.
Another option I thought about was importing this as `cognateclass` given that not other table has a column of this name, so nothing needs to be prefixed.

Which of these options is the least surprise and should be the default, and how should one tell the method that some other way is preferred?

**Comment by Anaphory** [comment]
With that new method, and some hacks to address #372, I can happily run automatic cognate coding using

    forms = LexStat.from_cldf(
        "../cldf/Wordlist-metadata.json",
        col="lect_id", row="concept_id", segments="segments", transcription="form")
    clusters = forms.cluster(method="sca", cluster_method="mcl", verbose=True)

and it seems to run well.

**Comment by LinguList** [comment]
I'd recommend not to use MCL for clustering though, it behaves without parameter changes identical with single linkage, and upgma linkage usually is more balanced...

**Comment by Anaphory** [comment]
Sure! That was just a bit of playing around with things and the last thing I had running to copy over to here.

**Comment by LinguList** [comment]
:)

**Comment by Anaphory** [comment]
I have now used my new class method with some regularity and noticed no problems. I'm still not very familiar with LingPy's testing setup, but happy to write some tests for it.

Shall I try to write some tests for reading the dataset in lingpy/lingpy/tests/test_data/cldf/?

Shall I write a test for outputting that dataset?

Would you like to see any other tests?

**Comment by LinguList** [comment]
I recommend to use the template test that we had (lingpy.convert.test_cldf in tests) and modify it accordling, maybe also modifying or adding a new small dataset. 

For writing tests outputting files, we use the WithTempDir class, for which you find an example in test_strings (also in lingpy.convert.tests), and there, look for the write_nexus test. 

Is this enough info to get started?

**Comment by Anaphory** [comment]
I've ported `lingpy.convert.test_cldf` to the new classmethod and will submit a pull request. There is actually no new output capability (sorry for my confusion).

- [X] Test import capability on the same level as the existing function
- [ ] Test with non-standard column headers
- [ ] Test metadata-free compliance
- [ ] Test fail on unknown data type
- [ ] Test classmethod functionality: Import as `LexStat` instead of `Wordlist`
- [ ] Check that cognate classes (imported from the cognate table) are accessible
