### ISSUE TITLE
the merge_geminates option of ipa2tokens overrides merge_vowels

### ISSUE THREAD

**Issue by murawaki** [lingpy/lingpy#371]
The ipa2token function has two options 'merge_geminates' and 'merge_vowels' among others.

Although the name 'merge_geminates' suggests it only covers consonants, it actually merges two identical tokens. And the 'merge_geminates' rule is applied after the 'merge_vowels' rule is applied.

An unexpected consequence of this is that when merge_geminates=True and merge_vowels=False are given, the latter is ignored. I do not think this is expected behavior.

**Comment by LinguList** [comment]
Sorry, could you provide an example to replicate?

**Comment by murawaki** [comment]
Looks like I got something wrong. Sorry for that.
