### ISSUE TITLE
Do not die from empty segment sequences

### ISSUE THREAD

**Issue by Anaphory** [lingpy/lingpy#372]
I have imported a `LexStat` where some entries in the `tokens` column are empty lists, and a few contain `None` because there are accidentally two subsequent spaces in the CSV.
LingPy dies on these entries with obscure and irrecoverable error messages, because the `__init__` method of `LexStat` does a lot of processing (eg. segmenting) without handing it of to separate methods, but instead uses the `add_entries` method to apply anonymous functions to all rows, and it's in these `lambda`s that assumptions are made.

Can we add a check earlier in `Wordlist.__init__` or `LexStat.__init__` that deals with empty forms and either drops them or raises an error? What would be a good place and implementation for that?

**Comment by LinguList** [comment]
Tell me quicklky: did you set "check" to true?

```
>>> lex = LexStat(bla, check=True)
```

This usually already provides you with a detailed lists of errors.

**Comment by LinguList** [comment]
See in our now accepted and soon to be published tutorial about this parameter [here](https://render.githubusercontent.com/view/ipynb?commit=3cd8033597bf3919d664c2d52f878b0510d151d7&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6c696e6770792f6c696e6770792d7475746f7269616c2f336364383033333539376266333931396436363463326435326638373862303531306431353164372f6e6f7465626f6f6b2e6970796e62&nwo=lingpy%2Flingpy-tutorial&path=notebook.ipynb&repository_id=93724516&repository_type=Repository#4.1-Checking-the-Data).

You can improve the check function by telling us what you would like tto have in lexstat, or by contributing more checks yourself.

**Comment by Anaphory** [comment]
I tried it, but was confused where it would place its output (I didn't see any and did not follow the code very deeply), and I *think* I got `[INFO] No obvious errors found in the data.`

Anyway, given how deadly empty forms are for the LexStat `__init__`, I would prefer if they were always checked, not just based on an optional boolean switch, but that a different switch would be introduced to demark whether empty forms are fatal or to be ignored.

My use case for empty forms, by the way, is mostly forms where speakers have the linguistic awareness to say “we don't have that word in our language, we use the Malay word instead”. Those rows appear in our database as rows with no form and no segments, but with comments.

**Comment by Anaphory** [comment]
I have seen that error. That is one of the
> obscure and irrecoverable error messages,
because while *true*, it's confusing and I think even cought by something else and re-raised as a more generic `ValueError`. (Sorry, I did some hacking to my checkout down this line, before noticing that it's not the optimal way to deal with the problem.)

Hm, for the moment maybe consider this issue a “note to self” to keep in mind, instead of something that needs action?

**Comment by LinguList** [comment]
Okay, we were writing in the same time. See above, what I mean. I think this is rather explicit for the moment. The "dialog" is something where @xrotwang said it is a bit problematic, as it prevents pipelines. I'd rather than tweaking lexstat more here, prefer to have an explicit routine for checking data on input, whether it's ready to be passed to lexstat. This would require additional steps for you to remove empty forms and re-insert them with 0-ids that would be good for edictor, but this is rather trivial. For data-checking, our tutorial is now providing the state of the art. Since it'll be published soon, the tutorial will represent the state-of-the-art of lingpy 2.6. So starting from there, we'd go for improvements in 2.7 and beyond.

We again wrote during the same time. So 

> Hm, for the moment maybe consider this issue a “note to self” to keep in mind, instead of something that needs action?

I agree. How should we flag those? I'd like to have some nice label for this kind of issues.

**Comment by Anaphory** [comment]
For the moment, I think it's appropriate to give the `from_cldf` method a `filter` parameter which is a function for rows to import, defaulting to `lambda row: row["Form"].strip()`, in particular because there might be other uses for an on-import filter like this (“Import only the Austronesian forms”, “Drop concept 345”, etc.)

**Comment by Anaphory** [comment]
Yes, but if I include them at load-time, they aren't in memory in the first place.

**Comment by LinguList** [comment]
But how important is that?
