### ISSUE TITLE
When aligning morphemes, LingPy aligns the whole word instead.

### ISSUE THREAD

**Issue by Anaphory** [lingpy/lingpy#384]
# Test code
```
import lingpy
import lingpy.compare.partial

lex = lingpy.compare.partial.Partial(
    {0: ["doculect", "concept", "ipa", "tokens", "partials"],
     1: ["l1", "first", "the_first", "t h e + f i r s t".split(), [1, 2]],
     2: ["l2", "first", "first", "f i r s t".split(), [2]]})


alm = lingpy.Alignments(lex, ref="partials")
alm.add_alignments(fuzzy=True)
alm.align(method='progressive')

for x in alm._data.values():
    print(x[-1])

```

# Expected output
```
['t', 'h', 'e', '◦', 'f', 'i', 'r', 's', 't']
['f', 'i', 'r', 's', 't']
```

# Actual output
```
['t', 'h', 'e', '◦', 't', 'h', 'e', '+', 'f', 'i', 'r', 's', 't']
['-', '-', '-', '-', 'f', 'i', 'r', 's', 't']
```

# Variants tested
I tested various variants. I tested both the current `lingpy` release and the current master branch.

## Not fuzzy
Without `alm.add_alignments(fuzzy=True)`, the alignment does not take partial cognates into account, but aligns according to the last (?) cognate class assigned. [This is a separate issue – this behaviour is unexpected. I would have assumed that class `[1, 2]` is different from `[2]`, or maybe that for multiple classes, the first is chosen, definitely not the last.]

    ['t', 'h', 'e', '+', 'f', 'i', 'r', 's', 't']
    ['-', '-', '-', '-', 'f', 'i', 'r', 's', 't']

## Setting morpheme separatator
With `from lingpy.settings import rcParams; rcParams['morpheme_separator'] = '+'`, the `◦` in the output is replaced by `+`, otherwise the behaviour is identical.

**Comment by Anaphory** [comment]
Ooof.

What *does* work is the following:

```
alm = lingpy.Alignments(lex, fuzzy=True, ref="partials")
alm.align(method='progressive')

for x in alm._data.values():
    print(x[-1])

```

The reason is that if `Alignments` gets some `ref`, it implicitly creates an alignment already. That alignment lives in the `msa` attribute, but does not show up in the new alignment column, which is filled with `0`s. Setting `fuzzy=True` on `add_alignment` does nothing (even though **that** is where the keyword argument is documented, **not** for `Alignment.__init__`), because the `.msa` for the `partials` `ref` is already filled with bogus global aligments.

I don't know a way out of this. Let's just try to document it and make it cleaner in LingPy3.

**Comment by LinguList** [comment]
Okay, the add_alignments is something that should not be used by yourself. It should be a private function. The place to use "fuzzy=True" is Alignments().

**Comment by LinguList** [comment]
If this is wrong in teh docs, this should be changed there. If it works there, I consider this as done, since Alignments() creates the Alignments.msa attribute. You could further split this, to have a separate function, but I find this behavior clear: Alignments() creates the msa-attribute, and this is filled by an alms.get_etymdict(ref='xxx'), and this again is behaving differently if its fuzzy or not. It seems, most of things to change are to modify the documentation and make add_alignments private.

**Comment by Anaphory** [comment]
Yes, the confusing bits are (1) that the docs talk about `add_alignment`, that function should not be advertised and the `fuzzy=True` bit should be documented in Alignments(), and (2) that `add_alignments` can set `fuzzy`; the `fuzzy` property is implicitly global for all possible objects of the alignment, so it should only be set at `__init__` and then never again.

Now that I know what's going on I find the discussion of `Alignment.msa` in the docs, and I find that it reflects what's going on. There might still be a better way of describing the interaction between the 0-initialized `ALIGNMENT` column and the naïvely-initialized (that's not ment as negative term) `.msa`. But I don't think that's worth it after cleaning up (1).
