### ISSUE TITLE
When aligning morphemes with scoredict=lex.cscorer, LingPy aligns the whole word instead.

### ISSUE THREAD

**Issue by Anaphory** [lingpy/lingpy#385]
We found out that the problem in #384 in mostly down to insufficient documentation.

Testing the undocumented and experimental feature `scoredict=lex.cscorer` in `align` like so

    alm = lingpy.Alignments(lex, row="concept", col="doculect",
                            segments="tokens", transcription="ipa",
                            ref="partialids",
                            fuzzy=True)
    alm.align(method='progressive', scoredict=lex.cscorer)
    alm.output('tsv', filename='aligned', ignore='all', prettify=False)

I noticed the same behiviour I noticed in #384.

In the process of making it a documented feature, we need to make sure that it works. I'm currently using partial alignments on dialects, where it's no big issue to re-invent the alignment score dict from scratch, but I am interested in using this feature for consistency between cognate coding and alignment over our whole database, so I'll have a look.

**Comment by Anaphory** [comment]
I see the first issue in 
https://github.com/lingpy/lingpy/blob/5181cbbbc549747c511c18922122f378152a17da/lingpy/align/sca.py#L931
Now, at that point, `.msa` has already been calculated and does not contain the information to match the `['a', 'l', 'a', 'p', 'ɔ']` in

    {'seq_id': '3 ("Tuhan / God")',
     'alignment': [['a', 'l', 'a', 'p', 'a', '-'], ['a', 'l', 'a', 'p', 'a', 'ŋ'], ['a', 'l', 'a', 'p', 'a', '-'], ['a', 'l', 'a', 'p', 'a', '-'], ['A', 'l', 'a', 'p', 'o', '-'], ['a', 'l', 'a', 'pː', 'ɔ', '-'], ['a', 'l', 'a', 'p', 'ɔ', '-'], ['a', 'l', 'a', 'p', 'a', '-'], ['a', 'l', 'a', 'k', '-', '-']],
     'taxa': ['alb', 'alk', 'bya', 'dul', 'hel', 'mun', 'pan', 'ter', 'war'],
     'dataset': 'lingpy-2018-09-18',
     'seqs': [['a', 'l', 'a', 'p', 'a'], ['a', 'l', 'a', 'p', 'a', 'ŋ'], ['a', 'l', 'a', 'p', 'a'], ['a', 'l', 'a', 'p', 'a'], ['A', 'l', 'a', 'p', 'o'], ['a', 'l', 'a', 'pː', 'ɔ'], ['a', 'l', 'a', 'p', 'ɔ'], ['a', 'l', 'a', 'p', 'a'], ['a', 'l', 'a', 'k']],
     'ID': [7521, 7520, 7522, 7519, 7526, 7524, 7527, 7523, 7528]}

to the – in this case – *first* morpheme of `7527`:

    ['11.A.V', '11.L.C', '11.A.V', '11.P.C', '11.U.V', '11._._', '11.L.C', '11.A.V', '11.H.C', '11.A.V', '11._._', '11.T.C', '11.A.V', '11.L.C', '11.A.V']

What would be the best way to allow this connection?

**Comment by LinguList** [comment]
In fact, lexstat should re-create the numbers and replace "11.U.V" by "+" proper. This would make the handling in our new basictypes.lists class consistent and also easily applicable. So already lexstat should create the numbers differently.

**Comment by Anaphory** [comment]
That is a deeper incision that my sporadic knowledge of LingPy interna permits me to do.

Also, you don't mean that this will already solve the problem here, do you? If you do, I fail to see how.

**Comment by LinguList** [comment]
I think that I should have a look at this some time later, but can't do so now. As the partial code is also dealing with lexstat.numbers without having a real problem, being directly based on the code, there is probably a simple solution for this thta I used when working with partial. This solution would then have to be added to alignments. 

But on another note: I don't know why you insist on using the lexstat scorer for the alignmetns after all?

Our most recent experiments show that the alignments are in fact better for partial alignments if you just use the simple methods, and we even have a new alignment algorithm that doesn't use SCA at all, it only looks at the prosodic templates. 

I'll eventually write this up and explain it more properly in a template. My gut feeling tells me that alignment problems may not need the heavy machinery they are given now with the SCA class and its guide trees, etc. At least I no longer use the lexstat.scorer when going for multiple alignments in Alignments.

**Comment by Anaphory** [comment]
> I don't know why you insist on using the lexstat scorer for the alignmetns after all?

Because I don't know any better? Naïvely, I expect alignments to be better when they take systematic sound correspondences into account, and naïvely, that is what I expected would happen (or be approximated) by passing the scorer as scoredict to the aligner.

**Comment by LinguList** [comment]
Fact is: you don't need that if you have good small morphemes boundaries nicely annotated, you just don't need it.

**Comment by LinguList** [comment]
But you are right: it should be offered by LingPy, yet the current lexstat.numbers are not properly parsed, so this is causing the trouble, and adjusting will be a bit more time-consuming than just chaning one line, but it should be possible.

**Comment by LinguList** [comment]
AND: don't assume the computer can do all for you: the alignments should be checked by humans anyway, so I'd rather say, at least for the time: make simple alignments, pass them ot the humans, and have them check them. If they find huge errors, this will most likely be due ot wrong cognates, etc., and if the alignments fail, well, adjusting them in edictor should be straightforward as long as you stick to smaller datasets...

Remind me via email to share the alternative method for alignments based on prosody, so you can check if it's feasible for your language data.
