### ISSUE TITLE
List standard correspondences between LingPy and CLDF

### ISSUE THREAD

**Issue by Anaphory** [lingpy/lingpy#399]
In #398 we discussed that it would be useful to have a lookup table between [CLDF property IDs](https://github.com/cldf/cldf/blob/master/terms.rdf) and LingPy column headers.

There I list

    corresponding = {
        'languageReference': 'doculect',
        'parameterReference': 'concept',
        # More well-defined and useful aliases go here
    }

I have several more in https://github.com/Anaphory/matrix_to_beastling/blob/master/Generic-LingPy-Wordlist-metadata.json

@LinguList has an implicit list somewhere, too, as does probably everyone who ever worked with these two things in the same project.

**Comment by Anaphory** [comment]
Another example: https://github.com/Anaphory/lingpycldf/blob/master/lingpycldf/lexstat.py#L88

**Comment by Anaphory** [comment]
Note that, different from some examples, I suggest a mapping between CLDF properties, not their default column names. `pycldf` needs some convincing to deal with the properties when reading tables line-by-line, but very much insists on the fact that column names/titles are arbitrary, so that is really what needs doing.

**Comment by xrotwang** [comment]
Yes! I agree! Sticking with the column names would just be another half-assed intermediate solution.

**Comment by LinguList** [comment]
Similar, of course, `Wordlist.row` is `Parameter_ID`.

**Comment by LinguList** [comment]
What complicates the matter, but it can still be handled, is that we need to spell out WHICH keywords are actually used by all the different algos. I can do that at some point, many have been already keyworded, so you COULD make it explitit, but usually you don't pay attention to it. E.g., `LexStat.numbers`, `LexStat.classes`.

**Comment by xrotwang** [comment]
Yes, I think a very good first step would be to stick to just one "metaphor", i.e. not talk about matrices and columns and rows in some classes and about concepts and doculects in others.

**Comment by LinguList** [comment]
I'll see if I find time to find my original posts on mappings, or to make a clean description of namespaces from scratch. If we delete all bad instances of `Wordlist.doculect`, we'll already make a big step, I think.

**Comment by Anaphory** [comment]
> is the equivalent of `Language_ID`, by all means, in cldf.

Note: You gave a :+1: to @xrotwang commenting that we should indeed use `languageReference` instead of `Language_ID`, and then continued to use `Language_ID` and `Parameter_ID` in your posts. I also often take that shortcut, but we need to be very careful to not fall into that trap.

**Comment by LinguList** [comment]
Yes. For lingpy variable naming, in wordlist namespace, the col is the language reference, and the row is the concept reference, and the language reference is currently called "langauge_id" in `wl.from_cldf`
