### ISSUE TITLE
Travis build failing

### ISSUE THREAD

**Issue by tresoldi** [lingpy/lingpy#401]
Travis is failing on Python 3.4 due to conflicts with `confirparser`:

```
Installed /home/travis/miniconda2/envs/condaenv/lib/python3.4/site-packages/UNKNOWN-0.0.0-py3.4.egg
error: The 'configparser>=3.5.0b2' distribution was not found and is required by clldutils
The command "python setup.py install" failed and exited with 1 during .
```

I cannot confirm if it is precisely the same repository, but it looks like the package was changed in conda a few hours ago: https://anaconda.org/anaconda/configparser

The easiest alternative seem to be moving from version `3.5.0b2` to `3.5.0`, i.e., the final, non-beta release.

**Comment by xrotwang** [comment]
Upgrading to [`clldutils>=2.6.3`](https://pypi.org/project/clldutils/2.6.3/) should fix this.
