### ISSUE TITLE
Allow networkx > 2.2

### ISSUE THREAD

**Issue by xrotwang** [lingpy/lingpy#417]
Curently, `networkx` is pinned to `<=2.2`, but version 2.4 of that library is already out. AFAICT that's mostly due to using `Graph.node[..]` to access nodes, which can be replaced with `Graph[...]` (at least for newer versions).

**Comment by LinguList** [comment]
Yes, I came over this in the past. What I suggest is: let's stop pinning. But we'd have to make sure that LingPy is also on line, as lingpy currently also pins networkx, right? I'd see what I can do in order to make sure that this is not a major new version of lingpy, but rather a 2.6.6.
