### ISSUE TITLE
plot_tree doesn't work

### ISSUE THREAD

**Issue by ilchec** [lingpy/lingpy#424]
There seems to be a conflict with the latest version of matplotlib, when I try to use plot_tree, the following error occurs:

ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'macosx' is currently running.

Mei-Shin and I tried to look for a solution and the problem seems to be that matplotlib is no longer using the the keyword "text.latex.unicode". Even if she forced it to avoid using tk backend, it couldn't run with another backend.

**Comment by LinguList** [comment]
Future updates of lingpy will remove ALL plotting routines, as we
recommend users to use matplotlib on their own or to use other packages,
e.g., splitstree or dendroscope. I suggest to just compute the newick
string and then store it in a file or copy-paste it to splits tree or
dendroscope.
