### ISSUE TITLE
path_component deprecated in clldutls 3.9

### ISSUE THREAD

**Issue by xrotwang** [lingpy/lingpy#433]
With PY3 it's no longer necessary to cast path components to `str`, thus we don't need `clldutils.path.path_component` anymore
https://github.com/lingpy/lingpy/blob/2929d0493aa19e011bb9e4e1741f75977aa84fc1/src/lingpy/util.py#L13

**Comment by xrotwang** [comment]
Currently, when using `clldutils==3.9`, that's a bit annoying, because we use `path_component` at **import** time - and `lingpy` is imported in many places, e.g. some `pylexibank` commands, which are imported whenever any `cldfbench` command is run, because they are looked up for the entry point.

**Comment by LinguList** [comment]
Would we make this a try/except for the time being, avoiding that we get problems with 3.6 and the like?

**Comment by xrotwang** [comment]
No - 3.9 is the clldutils version, **not** the Python version. `path_component` can simply be replaced by `str` - for any py>=3.6.

**Comment by xrotwang** [comment]
The reason this function still exists is that I forgot to throw it out when dropping PY2 compat, because it didn't use any `six` functionality. That was because encoding of filenames did not only depend on python version but also on OS.

**Comment by LinguList** [comment]
Ah, alright!

**Comment by LinguList** [comment]
So a bugfix release could be done then, right? I received some notes on missing data, due to the modified structure, which now makes the test-directory data links not appear in the way they used to, but this is mainly documentation. Yet, if we do this release, I'd put this together, and I'd also LIKE to see if I can use pylotree already instead of pycogent for tree handling.

**Comment by LinguList** [comment]
But if this is too far (which may well be), we just make the fix with 3.9, and that's it ;)

**Comment by xrotwang** [comment]
I'd vote for a bugfix release which just fixes this issue - which is somewhat annoying (and reminds me that doing stuff at import is just bad - in particular when entry points may be involved).

Rolling in pylotree shouldn't be done in a rush, I think, and happen with a couple more tests.

**Comment by LinguList** [comment]
Okay!

**Comment by xrotwang** [comment]
I fixed this locally by just replacing `path_component` with `str` - which worked. There also seems to be just one usage of `path_component` in all of lingpy. Note that other now deprecated functions may be called at runtime - i.e. not at import time. I'll run the tests with lingpy now, with clldutils 3.9.

**Comment by xrotwang** [comment]
Oh. quite a few warnings. I'll have a go at a PR for this.

**Comment by xrotwang** [comment]
Ok, wasn't that painful. So I think I'll roll in a bit of modernizing tests :)
