### ISSUE TITLE
Aligning partial cognates when a word has a single morpheme

### ISSUE THREAD

**Issue by XachaB** [lingpy/lingpy#436]
I am using lingpy and looking for partial cognates with `Partial` then aligning with `Alignments` and the `fuzzy=True` keyword. I have an edge case where a word is annotated as ['+', 'p', 'e'] (notice the leading '+') and detected in this cognate group: 

~~~
    [['θ', 'ɯ', '+', 'p', 'e'], 
     ['+', 'p', 'e'], 
     ['θ', 'o', '+', 'b', 'e', 'ʔ'], 
     ['ʂ', 'ɤ', '+', 'p', 'e'], 
     ['θ', 'ə', 'ŋ', '+', 'p', 'e', 'ŋ'],
     ['θ', 'ɯ̃', '+', 'p', 'e'], 
     ['s', 'e', 'i', 'n', '+', 'b', 'e', 'i']]. 
~~~

And the cognate IDS:

~~~
[[259, 260], [260], [259, 260], [259, 260], [259, 260], [259, 260], [259, 260]]
~~~

This results in the sequence numbers:

~~~
 [['1.P.C', '1.E.V'], [], ['5.P.C', '5.E.V', '5.H.c'], ['8.P.C', '8.E.V'], ['12.P.C', '12.E.V', '12.N.c'], ['16.P.C', '16.E.V'], ['17.P.C', '17.E.V', '17.I.V']]
~~~

In Alignments.align, this call then throws an exception, I believe because of the empty list:

https://github.com/lingpy/lingpy/blob/2929d0493aa19e011bb9e4e1741f75977aa84fc1/src/lingpy/align/sca.py#L964

The exception is:

~~~
  File "/home/sacha/bin/lexitools/src/lexitools/commands/correspondences.py", line 512, in find_cognates
    alm.align(method='progressive', scoredict=lex.cscorer)
  File "/home/sacha/bin/lexitools/env/lib/python3.8/site-packages/lingpy/align/sca.py", line 979, in align
    m.prog_align(**kw)
  File "/home/sacha/bin/lexitools/env/lib/python3.8/site-packages/lingpy/align/multiple.py", line 801, in prog_align
    self._get_pairwise_alignments(
  File "/home/sacha/bin/lexitools/env/lib/python3.8/site-packages/lingpy/align/multiple.py", line 313, in _get_pairwise_alignments
    alignments = calign.align_pairwise(
  File "/home/sacha/bin/lexitools/env/lib/python3.8/site-packages/lingpy/algorithm/cython/_calign.py", line 1714, in align_pairwise
    almA,almB,sim = globalign(
  File "/home/sacha/bin/lexitools/env/lib/python3.8/site-packages/lingpy/algorithm/cython/_calign.py", line 159, in globalign
    if traceback[i][j] == 3:
IndexError: list index out of range
~~~

Lines in the log above are not exact as I added a few prints to see the tokens, cogids, and numbers given above.

I find several such words starting in '+' e.g. in lexibank/starostinkaren. In this case, the word originates from (remember I'm coarsening the phonemic notation):

https://github.com/lexibank/starostinkaren/blob/master/cldf/forms.csv#L23

- Is this a bug ?
- Or is it that no words should start in "+" ? (it is a bit strange indeed)
- Or did I miss some required parameter somewhere ?

**Comment by LinguList** [comment]
These edge cases need to be handled on CLDF side.

If you use lexibank to create CLDF datasets, you can just check (we do
now routinely!):

cldfbench lexibank.check_phonotactics lexibank_datasets.py

This will tell you if you have edge cases and you can delete htem in
your data.

**Comment by XachaB** [comment]
So the problem is simply the initial "+" which should be removed, right ?

**Comment by LinguList** [comment]
BTW: starostinkaren is a dataset I haven't checked so far. This is also
the reason, why these cases can still be found there.

**Comment by XachaB** [comment]
I see, then maybe the issue is that it is in the lexicore list here: https://github.com/lexibank/lexicore/blob/main/datasets.txt

**Comment by LinguList** [comment]
The problem is the orthography profile, in which the initial `-` should
not be converted to a `+`.

The profile should be adjusted by adding:

^-    NULL
-$    NULL
-     +

That is what should be done.

**Comment by LinguList** [comment]
We are working on a new list, and this list has not really been approved
by me.

**Comment by XachaB** [comment]
Ok, thanks. Could you make sure to keep me up to date on the new list ? Re: the necessary changes for this particular dataset, do you want me to write an issue there so whoever is in charge of the dataset can do that ?

**Comment by LinguList** [comment]
There is no really new list. What we do is: we work on the database
paper. I checked some 100+ datasets during the past three months, it
took me some time, as you may imagine. In the same time, we also fixed
issues in pylexibank, in lingpy, etc. The goal is now to finish the
database paper, but until the code is settled there, we do not work with
any specific lexicore list, but rather use a set of some 20 datasets for
testing, in order to make sure there's no bias, since we have also some
correlation experiments, and we do not want to give the impression that
we tune the methods on the data.

I recommend you to do the same for the time being, until we have done
our final list. Ideally, pick some 20 datasets which are okay, and work
with them. Since access to CLDF has also improved now, the code on sound
correspondences will also require a thorough review later anyway.

**Comment by XachaB** [comment]
Ok, I'll manage a quick list until you have a final list for the database paper. Please make sure to tell me when you're through with that paper and corresponding list, so I can make the switch to these datasets.
