### ISSUE TITLE
Changing string processing in Trees

### ISSUE THREAD

**Issue by AetherPrior** [lingpy/lingpy#444]
Hi, I noticed that when I try to get a distance between a tree and itself, I get a value of 0.74
```
dist = tree1.get_distance(tree1,distance='grf',debug=True)  
print(dist)
```
> 0.7415730337078652

Upon checking what's happening, I noticed that an underscore was added to the spaces between language-names: 
![image](https://user-images.githubusercontent.com/39939017/236777748-c99e6d47-f939-4617-be02-5ad2e06c4c8a.png)

Here's the code for this, a comment asks if it's really necessary. I bring to your notice that it may cause issues for languages that are represented with more than one word:

        # prepare the trees [probably not necessary @lingulist]
        for tree in [treeA, treeB]:
            for old, new in [(";", ""), ("/", "-"), ("\n", "")]:
                tree = tree.replace(old, new)
        treeA = treeA.replace(" ", "_")

**Comment by LinguList** [comment]
Do you always get the distance of 0.74? Can you share the trees?

**Comment by LinguList** [comment]
Just confirmed: this is not the case, it is only for the particular tree you have there. Can I ask you please to normalize your language names (which is what I'd suggest anyway), so you don't have comma, space, etc., in them?

**Comment by LinguList** [comment]
There's a much better, newer newick package [here](https://github.com/dlce-eva/python-newick). On the long run, all tree functions in lingpy should make use of that package. So far, this is not the case. The new package handles spaces in names without a problem.

**Comment by LinguList** [comment]
But tree distance functions are not yet available, so the best way to proceed now is to make sure you use standard names for languages (alphanumeric only plus underscore) for your languages ONLY.

**Comment by AetherPrior** [comment]
Okay, noted. Thanks.  
Can we close this issue?

**Comment by LinguList** [comment]
If you confirm that the bug depends on the non-standard input from your side, yes, if you find the bug in other examples, we should leave it open.

**Comment by AetherPrior** [comment]
Confirmed, it happened due to the naming scheme.

**Comment by LinguList** [comment]
It is an implicit standard that one usually encounters when using newick across a couple of software pieces. I am not sure by now, if we documented it. But few software tools accept newick with spaces. So it is some "common sense" among those using Newick, that one should go for alphanumeric names with underscores for spaces.

**Comment by AetherPrior** [comment]
Okay. Thanks for letting me know. The issue is because of the naming format alone -- so if can be closed.

**Comment by LinguList** [comment]
Thanks for sharing this. We'll try and make this more consistent -- when only we find time -- integrating with the more recent newick package I mentioned.
