### ISSUE TITLE
lxml dependency breaks pip install in Python 3.8

### ISSUE THREAD

**Issue by arubehn** [lingpy/lingpy#453]
### Description

As the title suggests, it is currently not possible to install LingPy with ```pip install lingpy``` in Python 3.8 (and maybe older versions which I haven't tested), which fails with the following error message:
```
ERROR: Could not build wheels for lxml, which is required to install pyproject.toml-based projects.
```

This only seems to be the case for the latest version of lxml (4.9). A workaround for the problem is to install version 4.8 of lxml __before__ installing LingPy; afterwards, the installation of LingPy works as intended.

This problem does not occur in newer versions of Python; installation via pip (with dependencies to the latest version of lxml) works fine in Python 3.9 and 3.12.

### Reproduction steps

1. Create new virtual environment with Python 3.8 as base interpreter
2. Make sure no version of lxml is already installed or inherited from the base interpreter
3. Run ```pip install lingpy```

**Comment by LinguList** [comment]
Yes, and this gives me the chance to upload a fix to PIP, where we have 
the csvw"' with " and ' throwing a warning...
